platform :ios, '7.0'
pod 'AFNetworking', '~> 2.2'
pod 'SDWebImage', '~>3.6'
pod 'MBProgressHUD', '~> 0.5'
pod 'BDBOAuth1Manager', '1.4.0'
pod 'TTTAttributedLabel', '1.10.1'
pod 'PrettyTimestamp', '1.1'
